---
# Source: social-network/charts/unique-id-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: unique-id-service
  name: unique-id-service
spec: 
  replicas: 1
  selector:
    matchLabels:
      service: unique-id-service
  template:
    metadata:
      labels:
        service: unique-id-service
        app: unique-id-service
    spec:
      containers:
      - name: "unique-id-service"
        image: docker.io/deathstarbench/social-network-microservices:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
        command: 
        - UniqueIdService        
        volumeMounts:
        - name: unique-id-service-config
          mountPath: /social-network-microservices/config/jaeger-config.yml
          subPath: jaeger-config.yml
        - name: unique-id-service-config
          mountPath: /social-network-microservices/config/service-config.json
          subPath: service-config.json
      volumes:
      - name: unique-id-service-config
        configMap:
          name: unique-id-service
      hostname: unique-id-service
      restartPolicy: Always
