---
# Source: social-network/charts/social-graph-mongodb/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: social-graph-mongodb
  name: social-graph-mongodb
spec: 
  replicas: 1
  selector:
    matchLabels:
      service: social-graph-mongodb
  template:
    metadata:
      labels:
        service: social-graph-mongodb
        app: social-graph-mongodb
    spec:
      containers:
      - name: "social-graph-mongodb"
        image: docker.io/library/mongo:4.4.6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        args:
        - --config
        - /social-network-microservices/config/mongod.conf        
        volumeMounts:
        - name: social-graph-mongodb-config
          mountPath: /social-network-microservices/config/mongod.conf
          subPath: mongod.conf
      volumes:
      - name: social-graph-mongodb-config
        configMap:
          name: social-graph-mongodb
      hostname: social-graph-mongodb
      restartPolicy: Always
