apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: rate
  name: rate
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rate
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        io.kompose.service: rate
    spec:
      containers:
        - command:
            - rate
          image: divyanshus/hotelreservation:latest
          name: hotel-reserv-rate
          ports:
            - containerPort: 8084
          resources:
            requests:
              cpu: 2000m
            limits:
              cpu: 4000m
        - image: divyanshus/copper:non-init
          name: sidecar-bridge
          env:
          - name: RUST_LOG
            value: trace
          volumeMounts:
          - name: socks
            mountPath: /socks
          securityContext:
            privileged: true
            capabilities:
              add:
              - NET_ADMIN
                SYS_ADMIN
          command: ["ebpf-bridge"]
          args: ["driver", "--config", "/configs/ebpf-bridge-config.yaml"]
        - image: divyanshus/copper:non-init
          name: sidecar
          env:
          - name: RUST_LOG
            value: trace
          volumeMounts:
          - name: socks
            mountPath: /socks
          command: ["dyn-proxy"]
          args: ["run", "--config", "/configs/proxy-config.yaml"]
      volumes:
      - name: socks
        emptyDir: {}
      restartPolicy: Always
status: {}
