---
# Source: social-network/charts/home-timeline-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: home-timeline-service
  name: home-timeline-service
spec: 
  replicas: 1
  selector:
    matchLabels:
      service: home-timeline-service
  template:
    metadata:
      labels:
        service: home-timeline-service
        app: home-timeline-service
    spec:
      containers:
      - name: "home-timeline-service"
        image: docker.io/deathstarbench/social-network-microservices:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
        command: 
        - HomeTimelineService        
        volumeMounts:
        - name: home-timeline-service-config
          mountPath: /social-network-microservices/config/jaeger-config.yml
          subPath: jaeger-config.yml
        - name: home-timeline-service-config
          mountPath: /social-network-microservices/config/service-config.json
          subPath: service-config.json
      volumes:
      - name: home-timeline-service-config
        configMap:
          name: home-timeline-service
      hostname: home-timeline-service
      restartPolicy: Always
