---
# Source: social-network/charts/user-timeline-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: user-timeline-service
  name: user-timeline-service
spec: 
  replicas: 1
  selector:
    matchLabels:
      service: user-timeline-service
  template:
    metadata:
      labels:
        service: user-timeline-service
        app: user-timeline-service
    spec:
      containers:
      - name: "user-timeline-service"
        image: docker.io/deathstarbench/social-network-microservices:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
        command: 
        - UserTimelineService        
        volumeMounts:
        - name: user-timeline-service-config
          mountPath: /social-network-microservices/config/jaeger-config.yml
          subPath: jaeger-config.yml
        - name: user-timeline-service-config
          mountPath: /social-network-microservices/config/service-config.json
          subPath: service-config.json
      volumes:
      - name: user-timeline-service-config
        configMap:
          name: user-timeline-service
      hostname: user-timeline-service
      restartPolicy: Always
