---
# Source: social-network/charts/url-shorten-mongodb/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: url-shorten-mongodb
  name: url-shorten-mongodb
spec: 
  replicas: 1
  selector:
    matchLabels:
      service: url-shorten-mongodb
  template:
    metadata:
      labels:
        service: url-shorten-mongodb
        app: url-shorten-mongodb
    spec:
      containers:
      - name: "url-shorten-mongodb"
        image: docker.io/library/mongo:4.4.6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        args:
        - --config
        - /social-network-microservices/config/mongod.conf        
        volumeMounts:
        - name: url-shorten-mongodb-config
          mountPath: /social-network-microservices/config/mongod.conf
          subPath: mongod.conf
      volumes:
      - name: url-shorten-mongodb-config
        configMap:
          name: url-shorten-mongodb
      hostname: url-shorten-mongodb
      restartPolicy: Always
