---
# Source: social-network/charts/url-shorten-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: url-shorten-service
  name: url-shorten-service
spec: 
  replicas: 1
  selector:
    matchLabels:
      service: url-shorten-service
  template:
    metadata:
      labels:
        service: url-shorten-service
        app: url-shorten-service
    spec:
      containers:
      - name: "url-shorten-service"
        image: docker.io/deathstarbench/social-network-microservices:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
        command: 
        - UrlShortenService        
        volumeMounts:
        - name: url-shorten-service-config
          mountPath: /social-network-microservices/config/jaeger-config.yml
          subPath: jaeger-config.yml
        - name: url-shorten-service-config
          mountPath: /social-network-microservices/config/service-config.json
          subPath: service-config.json
      volumes:
      - name: url-shorten-service-config
        configMap:
          name: url-shorten-service
      hostname: url-shorten-service
      restartPolicy: Always
